version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask

  flask:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
    expose:
      - "8000"
    command: bash -c "./init_db.sh && gunicorn -w 4 -b 0.0.0.0:8000 app:app"

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
